[phases.install]
cmds = ["rm -rf node_modules/.vite", "npm ci"]

[phases.build]
cmds = ["npm run prisma:generate"]

[start]
cmd = "npx prisma migrate deploy --schema backend/prisma/schema.prisma && npm run start:api"
